In [1]:
import numpy as np
import pandas as pd

# Pandas

In [2]:
df_excel = pd.read_excel('dados/Chess.xlsx', sheet_name='Chess')

In [3]:
df_csv = pd.read_csv('dados/Tomato.csv', sep=',')

In [4]:
df_excel.head(4)

rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   

  opening_eco                            opening_name  opening_ply  
0         D10        Slav Defense: Exchange Variation            5  
1         B00  Nimzowitsch Defense: Kennedy Variation            4  
2         C20   King's Pawn Game: Leonardis Variation            3  
3         D02  Queen's Pawn Game: Zukertort Variation            3

In [5]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   rated           20058 non-null  bool   
 1   created_at      20058 non-null  float64
 2   last_move_at    20058 non-null  float64
 3   turns           20058 non-null  int64  
 4   victory_status  20058 non-null  object 
 5   winner          20058 non-null  object 
 6   increment_code  20058 non-null  object 
 7   white_id        20058 non-null  object 
 8   white_rating    20058 non-null  int64  
 9   black_id        20058 non-null  object 
 10  black_rating    20058 non-null  int64  
 11  opening_eco     20058 non-null  object 
 12  opening_name    20058 non-null  object 
 13  opening_ply     20058 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(7)
memory usage: 2.0+ MB


In [6]:
df_csv.tail(4)

Date Unit  Minimum  Maximum  Average  Market
2737  2021-05-10   Kg       10       15     12.5  Tomato
2738  2021-05-11   Kg       10       15     12.5  Tomato
2739  2021-05-12   Kg       30       35     32.5  Tomato
2740  2021-05-13   Kg       35       40     37.5  Tomato

In [7]:
df_csv.shape

(2741, 6)

In [8]:
df_csv.describe()

Minimum      Maximum      Average
count  2741.000000  2741.000000  2741.000000
mean     35.089748    41.281284    38.185516
std      16.648425    17.364135    16.970949
min       8.000000    12.000000    10.000000
25%      22.000000    30.000000    25.000000
50%      30.000000    38.000000    35.000000
75%      45.000000    50.000000    47.500000
max     115.000000   120.000000   117.500000

In [9]:
df_csv.describe().T

count       mean        std   min   25%   50%   75%    max
Minimum  2741.0  35.089748  16.648425   8.0  22.0  30.0  45.0  115.0
Maximum  2741.0  41.281284  17.364135  12.0  30.0  38.0  50.0  120.0
Average  2741.0  38.185516  16.970949  10.0  25.0  35.0  47.5  117.5

In [10]:
df_excel.head()

rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   
4   True  1.504030e+17  1.504030e+17     95           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   
4           30+3      nik221107          1523  adivanov2009          1469   

  opening_eco                            opening_name  opening_ply  
0         D10        Slav Defense: Exchange Variation            5  
1         B00  Nimzowitsch Defense: Kennedy Variation            4  
2         C20   King's Pawn Game: Leonardis Variation            3  
3         D02  Queen's Pawn Game: Zukertort Variation            3  
4         C41                        Philidor Defense            5

In [11]:
df_excel.head()

rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   
4   True  1.504030e+17  1.504030e+17     95           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   
4           30+3      nik221107          1523  adivanov2009          1469   

  opening_eco                            opening_name  opening_ply  
0         D10        Slav Defense: Exchange Variation            5  
1         B00  Nimzowitsch Defense: Kennedy Variation            4  
2         C20   King's Pawn Game: Leonardis Variation            3  
3         D02  Queen's Pawn Game: Zukertort Variation            3  
4         C41                        Philidor Defense            5

In [12]:
set(df_excel['victory_status'])

{'draw', 'mate', 'outoftime', 'resign'}

In [13]:
df_excel['victory_status'].unique()

array(['outoftime', 'resign', 'mate', 'draw'], dtype=object)

In [14]:
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market
0  2013-06-16   Kg       26       32     29.0  Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato

In [15]:
def categorizar_tomate_media(media):
    if media >= 40 and media <= 70:
        return 'Medium Tomato'
    elif media < 40:
        return 'Small Tomato'
    else:
        return 'Large Tomato'

In [16]:
df_csv['Tomato Size'] = df_csv['Average'].apply(categorizar_tomate_media)

In [17]:
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market   Tomato Size
0  2013-06-16   Kg       26       32     29.0  Tomato  Small Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato  Small Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato  Small Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato  Small Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato  Small Tomato

In [18]:
df_csv.groupby(['Tomato Size']).describe()

Minimum                                                      \
                count       mean       std   min   25%   50%   75%    max   
Tomato Size                                                                 
Large Tomato    149.0  75.744966  7.324666  65.0  70.0  75.0  80.0  115.0   
Medium Tomato   954.0  47.818658  8.203065  30.0  40.0  45.0  55.0   65.0   
Small Tomato   1638.0  23.978022  7.175572   8.0  18.0  25.0  30.0   38.0   

              Maximum             ...              Average             \
                count       mean  ...   75%    max   count       mean   
Tomato Size                       ...                                   
Large Tomato    149.0  82.583893  ...  85.0  120.0   149.0  79.164430   
Medium Tomato   954.0  55.009434  ...  60.0   75.0   954.0  51.414046   
Small Tomato   1638.0  29.528694  ...  35.0   44.0  1638.0  26.753358   

                                                        
                    std   min   25%   50%   75%    max  
Tomato Size                                             
Large Tomato   7.367396  70.5  75.0  77.5  82.5  117.5  
Medium Tomato  8.272792  40.0  45.0  50.0  57.5   70.0  
Small Tomato   7.191735  10.0  21.5  27.5  32.5   39.5  

[3 rows x 24 columns]

In [19]:
filtro = df_csv['Average'] < 40
df_csv.loc[filtro]

Date Unit  Minimum  Maximum  Average  Market   Tomato Size
0     2013-06-16   Kg       26       32     29.0  Tomato  Small Tomato
1     2013-06-17   Kg       20       25     22.5  Tomato  Small Tomato
2     2013-06-18   Kg       22       26     24.0  Tomato  Small Tomato
3     2013-06-19   Kg       24       28     26.0  Tomato  Small Tomato
4     2013-06-20   Kg       22       26     24.0  Tomato  Small Tomato
...          ...  ...      ...      ...      ...     ...           ...
2736  2021-05-09   Kg       10       15     12.5  Tomato  Small Tomato
2737  2021-05-10   Kg       10       15     12.5  Tomato  Small Tomato
2738  2021-05-11   Kg       10       15     12.5  Tomato  Small Tomato
2739  2021-05-12   Kg       30       35     32.5  Tomato  Small Tomato
2740  2021-05-13   Kg       35       40     37.5  Tomato  Small Tomato

[1638 rows x 7 columns]

# Numpy

In [20]:
arr_zeros = np.zeros((4, 6))
print(arr_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [21]:
arr_ones = np.ones((3, 4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
arr_random = np.random.rand(3, 4)
print(arr_random)
print()
print(arr_random.shape)

[[0.07498914 0.40068244 0.84307553 0.35080152]
 [0.07870935 0.85235809 0.31578063 0.92941119]
 [0.46246314 0.34147964 0.82839288 0.76386251]]

(3, 4)


In [23]:
arr_rand_reshape = arr_random.reshape((4, 3))
print(arr_rand_reshape)

[[0.07498914 0.40068244 0.84307553]
 [0.35080152 0.07870935 0.85235809]
 [0.31578063 0.92941119 0.46246314]
 [0.34147964 0.82839288 0.76386251]]
