In [1]:
import numpy as np
import pandas as pd

In [2]:
# Escalar, Vetor e Matriz

# Escalar -> Número (Tensor de Ordem 0 - Um ponto)
x = 2
print('Escalar: ', x, '\n')

# Vetor com três elementos escalares
x2 = np.array([1, 2, 3])
print('Vetor: ', x2, '\n')

# Matriz com três elementos vetores com elementos escalares (Matriz coluna)
x3 = np.array([[1], [2], [3]])
print('Matriz:\n', x3, '\n')

# Matriz (Matriz Tradicional)
x4 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print('Matriz:\n', x4, '\n')

Escalar:  2 

Vetor:  [1 2 3] 

Matriz:
 [[1]
 [2]
 [3]] 

Matriz:
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 



In [3]:
# Pandas Series -> Vetor
# Pandas Dataframe -> Array

pd.DataFrame({'coluna_1': np.array([1, 2, 3, 4, 5]),
              'coluna_2': np.array([1, 2, 3, 4, 5])})

coluna_1  coluna_2
0         1         1
1         2         2
2         3         3
3         4         4
4         5         5

In [4]:
# Exemplo de Operação (Combinação Linear de Elementos)

print(x2, '\n')
print(x3, '\n')
print(x2 + x3)

[1 2 3] 

[[1]
 [2]
 [3]] 

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [5]:
print(x4, '\n')
print(x4 + x4)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [6]:
# Na multiplicação, o número de colunas da primeira matriz precisa ser igual
# ao número de linhas da segunda matriz

# A matriz resultado da operação terá o mesmo número de linhas da primeira
# matriz e o mesmo número de colunas da segunda matriz

In [7]:
print(x3, '\n')
print(x4)

[[1]
 [2]
 [3]] 

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
np.dot(x4, x3)

array([[14],
       [14],
       [14]])

In [9]:
# Criando matrizes de elementos neutros para operações de soma ou multiplicação

print(np.zeros((3, 3)))
print()
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
