In [1]:
import numpy as np

In [2]:
# Escalar, Vetor e Matriz

# Escalar -> Número (Tensor de Ordem 0)
x = 2
print('Escalar: ', x, '\n')

# Vetor com três elementos escalares
x2 = np.array([1, 2, 3])
print('Vetor: ', x2, '\n')

# Matriz com três elementos vetores com elementos escalares (Matriz coluna)
x3 = np.array([[1], [2], [3]])
print('Matriz:\n', x3, '\n')

# Matriz (Matriz Tradicional)
x4 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print('Matriz:\n', x4, '\n')

Escalar:  2 

Vetor:  [1 2 3] 

Matriz:
 [[1]
 [2]
 [3]] 

Matriz:
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 

