In [1]:
import numpy as np
from scipy import stats

In [2]:
usuarios = np.array([[8, 0, 3, 4, 6], [5, 6, 1, 8, 9], [8, 0, 0, 5, 10]])
usuario_novo = [8, 0, 2, 3, 0]
nao_assistidos = [0, 1, 0, 0, 1]
catalogo = ['Round 6', 'Breaking Bad', 'You', 'La Casa de Papel', 'Narcos']

In [3]:
similaridade = 3 * [0]

In [4]:
for i in range(0, 3): # usuarios
    tmp = usuarios[i, :]
    tmp_usuario = [t for n, t in zip(usuario_novo, tmp) if n != 0]
    tmp_usuario_novo = [n for n in usuario_novo if n != 0]
    similaridade[i] = stats.pearsonr(tmp_usuario, tmp_usuario_novo)[0]

In [5]:
similaridade

[0.9994237971287664, 0.23621543814299703, 0.8723686098443353]

In [6]:
peso_nota = np.zeros((3, 5))

In [7]:
for i in range(3): # usuarios
    for j in range(5): # catalogo
        peso_nota[i][j] = nao_assistidos[j] * usuarios[i][j] * similaridade[i]

In [8]:
print(peso_nota)

[[0.         0.         0.         0.         5.99654278]
 [0.         1.41729263 0.         0.         2.12593894]
 [0.         0.         0.         0.         8.7236861 ]]


In [9]:
notas_acumuladas = np.sum(peso_nota.T, axis=1)
print(notas_acumuladas)

[ 0.          1.41729263  0.          0.         16.84616782]


In [10]:
peso_temp = peso_nota
peso_temp[peso_nota > 0] = 1
print(peso_temp)

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]


In [11]:
similaridade_temp = np.zeros((3, 5))

In [12]:
for i in range(3): # usuarios
    for j in range(5): # catalogo
        similaridade_temp[i][j] = peso_temp[i][j] * similaridade[i]

In [13]:
print(similaridade_temp)

[[0.         0.         0.         0.         0.9994238 ]
 [0.         0.23621544 0.         0.         0.23621544]
 [0.         0.         0.         0.         0.87236861]]


In [14]:
similaridade_acumulada = np.sum(similaridade_temp.T, axis=1)
print(similaridade_acumulada)

[0.         0.23621544 0.         0.         2.10800785]


In [15]:
nota_final = [0] * 5

In [16]:
for i in range(5):
    if similaridade_acumulada[i] > 0:
        nota_final[i] = notas_acumuladas[i] / similaridade_acumulada[i]
    else:
        nota_final[i] = 0

In [17]:
print(nota_final)

[0, 6.0, 0, 0, 7.991510972567145]


In [18]:
notas_ordenadas = sorted(range(len(nota_final)), key=nota_final.__getitem__)\
                  [::-1][0:sum(nao_assistidos)]
print(notas_ordenadas)

[4, 1]


In [19]:
for i in notas_ordenadas:
    print(catalogo[i], nota_final[i])

Narcos 7.991510972567145
Breaking Bad 6.0
